[package]
name = "Baler"
version = "0.2.1"

[dependencies]
UnicodeWidth = { git = "https://github.com/meadow-lang/UnicodeWidth", version = "0.2.0" }
UnicodeLinebreak = { git = "https://github.com/meadow-lang/UnicodeLinebreak", version = "0.2.0" }
